### ISSUE TITLE
crashes when using Go 1.13+

### ISSUE THREAD

**Issue by protosam** [protosam/go-libnss#7]
When using go-libnss in 1.13 or newer, connections over ssh will crash when nss is relying on `net/http`.

The cause seems to be due to non-cooperative preemption from [this proposal](https://go.googlesource.com/proposal/+/master/design/24543-non-cooperative-preemption.md) in Go 1.13+ per this issue: https://github.com/golang/go/issues/24543

To figure out the level of effort to correct this when using go-libnss requires understanding the runtime scheduler. There's some explanation on it [here](https://discourse.world/h/2020/05/23/GO-Scheduler%3ANow-Not-Cooperative%3F) that may or may not be outdated.

First thought is to see if using a different signal works. My second though is perhaps making an attempt to replace the parts with stubs similar to windows to just disable preemption all together.

For reference later: 
- [runtime.preemptM(mp *m)](https://github.com/golang/go/blob/d15481b8c7f5f73a8b987a0c1deea04659ed0bb0/src/runtime/preempt.go#L218-L235) contains the code that sends the preemption signal. 
- [runtime.sigPreempt](https://github.com/golang/go/blob/d15481b8c7f5f73a8b987a0c1deea04659ed0bb0/src/runtime/signal_unix.go#L43-L73) is the signal that is used for preemption.

Things to look into leveraging for a fix.
- [compiler documentation](https://pkg.go.dev/cmd/compile)
- - go:linkname to get access to unexported package parts. Not sure if it's writable or not, but it's something.
- - does go:nosplit just disable the preemption it placed on a function that is used as a goroutine?
- Use reflect in init() to patch the methods and/or `runtime.sigPreempt`

This issue was mentioned in #2  and #6.

**Comment by maraino** [comment]
In my experience, it was Go 1.14+ even without `net/http`. 

The problem for `net/http` I mentioned was because you should not mix threads (goroutines in the net/http package) and forks on SSHD, and it was a PAM module.

**Comment by protosam** [comment]
My goal for this issue is to get Go 1.17+ working and tag the current commit as-is for archaic use.

**Comment by maraino** [comment]
Step to reproduce the problem:
1. Follow the steps to compile and instal [go-libnss example](https://github.com/protosam/go-libnss/blob/7d15cc62567ddad368949b33fdd3173c4e971b50/example/README.md). Depending on your SO the path where the library should be installed might be different.
2. Run top on testguy1
```console
$ sudo su testguy1
$ top

	signal 23 (URG) was caught by top, please
	send bug reports to <procps@freelists.org>
```

Notes: 
* The same problem happens on a different user is there's a process owned by testguy1.
* The crash doesn't happen always, but it's pretty consistent.

**Comment by protosam** [comment]
Going to close this. I spent some time looking further into this and my conclusion is that Go is not the right tool to interface with nss and pam. Any shared libraries made with CGO will inherit any design choices of the Go runtime as well as drawbacks involved with interoperability. This seems to hold true for Rust, Swift, and to my surprise C++. As such, it makes more sense to either make an ldap service to interface with libnss-ldapd/sssd, or write libnss modules in C.
